### ISSUE TITLE
Add pull-request-header and pull-request-footer to action's input

### ISSUE THREAD

**Issue by lacolaco** [googleapis/release-please-action#1001]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**

Since v4, `pull-request-header` and `pull-request-footer` are only set in config JSON file. In JSON, it is not convenient to set multi-lines string. Until v3, I could read the content from file and pass it to the action's input like below;

```
- name: Get header
  id: release-please-header
  run: echo "content=$(cat release-please-header.md)" >> $GITHUB_OUTPUT
- use: googleapis/release-please@v3
  with: 
    pull-request-header: ${{ steps.release-please-header.outputs.content }}
```

**Describe the solution you'd like**

Add `pull-request-header` and `pull-request-footer` inputs to release-please-actions.

**Describe alternatives you've considered**

**Additional context**
