### ISSUE TITLE
Release please creating new release PR every time I merge the release PR

### ISSUE THREAD

**Issue by AlbertHernandez** [googleapis/release-please-action#1006]
Hi! I am trying to adopt release-please in order to release a [npm package](https://github.com/AlbertHernandez/typescript-library-template). However, what is happening is that everytime I merge the PR that is created by release-please, a new PR is being created

The issue is in this [public](https://github.com/AlbertHernandez/typescript-library-template) repository. My configuration is:

`release-please.yml`

```yml
name: 'Release Please'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
```

`release-please-config.json`

```json
{
  "bootstrap-sha": "b6b9602f90f039f6da582ce32e36239cd69917cf",
  "packages": {
    ".": {
      "include-component-in-tag": false,
      "release-type": "node",
      "draft": false,
      "prerelease": false
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

`.release-please-manifest.json:`

```json
{
  ".": "1.9.0"
}
```

What I see as a result is:

First, I the [release PR](https://github.com/AlbertHernandez/typescript-library-template/pull/222) is created:

![CleanShot 2024-06-08 at 10 22 42@2x](https://github.com/googleapis/release-please-action/assets/29106063/a57fdb2f-240a-4d70-8ba5-050bce079ed9)

After merging that PR, [release-please action](https://github.com/AlbertHernandez/typescript-library-template/actions/runs/9427323105/job/25971306942) runs:

![CleanShot 2024-06-08 at 10 23 55@2x](https://github.com/googleapis/release-please-action/assets/29106063/b88cd498-5330-4884-800c-12cbf3e806c6)

After this finish, it creates again a new [release PR](https://github.com/AlbertHernandez/typescript-library-template/pull/223) with a new version:

![CleanShot 2024-06-08 at 10 24 57@2x](https://github.com/googleapis/release-please-action/assets/29106063/ec47d6ba-e04f-4e47-8d3f-3ce7addd9624)

I have tried multiple things, also looking other's configuration, changing some options to see if it was related to some specific property... but after investigating for a while I am not being able to make it work correctly :(

Can anyone help me to understand what's happening and how to fix it? Thanks in advance!
