### ISSUE TITLE
release branch name

### ISSUE THREAD

**Issue by Hyodori04** [googleapis/release-please-action#1019]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
In monorepo, i want to make various relase branch
- What code you've already tried

release-plase-config.json
```
{
  "include-component-in-tag": true,
  "tag-separator": "@",
  "release-type": "simple",
  "separate-pull-requests": true,
  "changelog-sections": [{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"refactor","section":"Refactoring","hidden":false},{"type":"fix(deps)","section":"Dependency Update","hidden":false},{"type":"test","section":"Tests","hidden":false}],
  "packages": {
    "web/apps/service1": {
      "package-name": "service1",
      "component": "service1",
      "include-component-in-tag": true,
      "separate-pull-requests": true
    }
  }
}
```

acitions.yml

```
name: Service1-ReleasePlease

on:
  push:
    branches:
      - main
    paths:
      - "web/apps/service1/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "web/apps/service1"
          release-type: simple
          config-file: default
          manifest-file: default
          include-component-in-tag: 'true'
      - name: deploy
        if: ${{ steps.release.outputs['web/apps/service--release_created'] }}
        run:
          echo "deploy"
```

- Any error messages you're getting

<img width="575" alt="스크린샷 2024-07-10 오후 2 25 15" src="https://github.com/googleapis/release-please-action/assets/57362573/74651634-49ec-405c-aa35-c524a500de2f">

release-please--branches--main is made but in comparing v3
release-please--branches--main--components--service is should made
