### ISSUE TITLE
Include other commit prefixes to changelog.md from pre-defined CHANGELOG_SECTIONS

### ISSUE THREAD

**Issue by janezlapajne** [googleapis/release-please-action#1020]
I use release-please action and it works like a charm!

I employ simple setup for python:

```
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: python
```

I have seen that most commit prefixes are not written to changelog file, probably based on hidden flag defined in [CHANGELOG_SECTIONS](https://github.com/googleapis/release-please/blob/ace2bd5dc778f83c33ad5dee6807db5d0afdba36/src/strategies/python.ts#L31) 

Is there an option in the github action itself to define which prefixes to include? If not, what is the most elegant solution to achieve this?

Thank you in advance!
