### ISSUE TITLE
getting error: release-please failed: fetch failed

### ISSUE THREAD

**Issue by victor-wang-anz** [googleapis/release-please-action#1021]
Thanks for stopping by to ask us a question! Please make sure to include:
- I just upgraded the release please to v4 and updated my config, but now getting error: release-please failed: fetch failed

below is my yaml:

```
      - name: Run Release Please
        uses: ./.actions/release-please-action
        with:
          token: xxx
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: main
          proxy-server: localhost:3128
```

error:
Run ./.actions/release-please-action
  with:
    token: ***
    config-file: release-please-config.json
    manifest-file: .release-please-manifest.json
    target-branch: main
    proxy-server: xxx
    repo-url: xxx
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    fork: false
    include-component-in-tag: false
    skip-github-release: false
    skip-github-pull-request: false
    changelog-host: https://github.com
Running release-please version: 1[6](https://github.com/xxx/actions/runs/xxx/job/xxx#step:5:6).12.0
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
Error: release-please failed: fetch failed

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
