### ISSUE TITLE
Release-please is adding commits to the changelog that are already added to previous changelog versions

### ISSUE THREAD

**Issue by majorgilles** [googleapis/release-please-action#1050]
#### Environment details

  - Programming language: Python
  - OS: ubuntu-latest
  - Language runtime version: 3.12
  - Package version: v4 of action

#### Steps to reproduce

---

Config files

[.release-please-manifest.json](https://github.com/user-attachments/files/17585333/default.release-please-manifest.json)
[release-please-config.json](https://github.com/user-attachments/files/17585334/release-please-config.json)

--- 

YAML of github action
```yml
name: 🚀 release-please

on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: trunk
          token: ${{ SOME_TOKEN }}
 
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
```

  1. Add a commit message (e.g. starting with "feat: ") and push / merge to trunk
  2. The release please action runs

points 3-5 (having an `autorelease: pending` label) may not be related to the issue
  3. it finds (apparently) an `autorelease: pending` branch (despite me having merged the PR - this may be a totally separate issue)
  4. I remove the autorelease: pending label
  5. I rerun the action, which creates a PR this time.
 
  6. This PR contains commits already released as can be seen here.
[CHANGELOG.md](https://github.com/user-attachments/files/17585363/CHANGELOG.md)

Thanks!
