### ISSUE TITLE
Different release-please configs in same repository and release from brach

### ISSUE THREAD

**Issue by raulmartinezr** [googleapis/release-please-action#1059]
Thanks for stopping by to ask us a question! Please make sure to include:

**- What you're trying to do**
Configure multiple relsease please configs in same github repo using same branch (master) as target 

**- What code you've already tried**

two base paths in repo (backend/cloud and backend/edge) with different configs and manifest

```
      - uses: googleapis/release-please-action@main # googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: backend/edge/release-please-config-backend-edge.json
          manifest-file: backend/edge/release-please-manifest-backend-edge.json
```
```
      - uses: googleapis/release-please-action@main # googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: backend/cloud/release-please-config-backend-edge.json
          manifest-file: backend/cloud/release-please-manifest-backend-edge.json
```

**- Any error messages you're getting**

Release PR are being overriden when action is triggered as both configuration uses the same branch `release-please--branches--master`. Would it be possible to use different configs with diferent PR branches but keeping same target branch?
