### ISSUE TITLE
Can't use a dynamic release-as config after v4 migration

### ISSUE THREAD

**Issue by onderceylan** [googleapis/release-please-action#1068]
We have a use case of creating a hotfix release with a self calculated patch version, of which we need to pass to the action as the `release-as` config variable. This config variable is calculated dynamically and is not committed to the repository.

v4 version requires users to use a config file to set the `release-as` config. And, config files cannot be read from the filesystem, and has to be committed to the repo and be fetched from a repo & branch ref. As for the hotfix use case, this config is a dynamic variable, and can't be committed to the repo. Therefore, we can't use a dynamic `release-as` config after v4 migration.

On a side note, if release-please upstream package would have supported loading config files from a local filesystem, we would not have this issue. It's reported separately on https://github.com/googleapis/release-please-action/issues/1017.

#### Environment details

  - Programming language: Node.js / TypeScript
  - OS:  ubuntu-22.04
  - Language runtime version: Node.js 22.11.0
  - Package version: v4.1.3

#### Steps to reproduce

  1. Have a config file that will be used for hotfix releases - `release-please-config.hotfix.json`
```JSON
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "release-type": "simple",
  "pull-request-title-pattern": "chore(release): hotfix release ${version}",
  "pull-request-header": "🚨 Hotfix Release",
  "label": "hotfix",
  "release-label": "hotfix",
  "packages": {
    ".": {}
  }
}

```
  2. Have a step in the workflow to dynamically update the config file
```YAML
- name: Update hotfix config version
  run: |
    jq --arg version "${{ steps.hotfix-version.outputs.new_version }}" \
      '. + {"release-as": $version}' \
      release-please-config.hotfix.json > temp.json && mv temp.json release-please-config.hotfix.json

    echo "Updated hotfix config:"
    cat release-please-config.hotfix.json
```

  3. Run the workflow with the hotfix config file
```YAML
- uses: googleapis/release-please-action@v4
  id: release
  with:
    config-file: release-please-config.hotfix.json
    manifest-file: .release-please-manifest.json
    target-branch: ${{ inputs.hotfix-branch }}
    token: ${{ steps.generate-token.outputs.token }}
```
