### ISSUE TITLE
Unable to make release please work after an accidental major version bump ( release-please failed: Resource not accessible by integration) 

### ISSUE THREAD

**Issue by praveenpuglia** [googleapis/release-please-action#1070]
Hi!

My package was at 2.7.6. I introduced release-please and it thought it should make a v.4.0.0 based on the commits and changelog. 

It wasn't supposed to be merged and released that way but it happened. I removed the tag v4.0.0 but ever since, I have not been able to get release please to work and release a version like 2.7.7 and so on. 

Here's my config file for the workflow. 
<details><summary>Workflow</summary>
<p>

```yml
name: release-please
permissions: write-all
on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, 'release-please')}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Run release-please
        uses: googleapis/release-please-action@v4
```

</p>
</details> 

I have tried the `bootstrap-sha` and `last-release-sha` options but they didn't change anything. 

Here's what I am getting in the workflow instead. 
```
Run googleapis/release-please-action@v4
  with:
    token: ***
    repo-url: smallcase/sc-fe-utils
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    fork: false
    include-component-in-tag: false
    skip-github-release: false
    skip-github-pull-request: false
    changelog-host: https://github.com
  env:
    VOLTA_HOME: /opt/hostedtoolcache/volta/[2](https://github.com/smallcase/sc-fe-utils/actions/runs/12485681896/job/34844793233#step:4:2).0.2/x64
Running release-please version: 16.12.0
❯ Fetching release-please-config.json from branch master
❯ Fetching .release-please-manifest.json from branch master
✔ Building releases
✔ Building strategies by path
❯ .: node
❯ Found pull request #11[4](https://github.com/smallcase/sc-fe-utils/actions/runs/12485681896/job/34844793233#step:4:4): 'chore(master): release 4.0.0'
✔ Building release for path: .
❯ type: node
❯ targetBranch: master
❯ Fetching package.json from branch master
✔ Creating 1 releases for pull #[11](https://github.com/smallcase/sc-fe-utils/actions/runs/12485681896/job/34844793233#step:4:11)4
Error: release-please failed: Resource not accessible by integration
```

If I understand this correctly, it's still trying to pull data from a v4.0.0 that doens't exist anymore. 

I have tried enabling / disabling the actions permissions from GitHub settings as well but to no avail. 

What am I doing wrong? How can I reset everything?
