### ISSUE TITLE
Can you run this action in a private repository?

### ISSUE THREAD

**Issue by 0xangelo** [googleapis/release-please-action#1076]
So far I've tried the following workflow file:
```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.PERSONAL_TOKEN }}
```

Where `PERSONAL_TOKEN` is my personal access token, and I have write permissions to the private repository where I'm trying to use this action.

Config files are the standard `.release-please-manifest.json` and `release-please-config.json`.

However, whenever the action runs I get this in the logs:
```
Run googleapis/release-please-action@v4.1.3
  with:
    token: ***
    repo-url: REDACTED
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    fork: false
    include-component-in-tag: false
    skip-github-release: false
    skip-github-pull-request: false
    changelog-host: https://github.com
Running release-please version: 16.12.0
Error: release-please failed: Not Found
