### ISSUE TITLE
releases cannot be marked as prereleases

### ISSUE THREAD

**Issue by OdinValholl** [googleapis/release-please-action#1077]
Recently, releases can no longer be created as prereleases by setting the `"prerelease": true` configuration in the `release-please-config.json` file.

Can this issue currently be confirmed?

My `release-please-config.json` looks like this:
```yaml
{
  "pull-request-title-pattern": "Release(${component}) v${version}",
  "prerelease": true,
  "include-v-in-tag": true,
  "include-component-in-tag": true,
  "tag-separator": "-",
  "separate-pull-requests": true,
  "component-no-space": true,
  "packages": {
    ".": {
      "package-name": "any-app",
      "component": "any-app",
      "release-type": "simple"
    }
  }
}
```

In addition, with this [scheme](https://github.com/googleapis/release-please/blob/main/schemas/config.json) I couldn't find out exactly at which level the `prerelease-type` can be set because it doesn't quite agree with the documentation in the README.

As further information, when setting up my project I noticed that the autoreleases could not be created because the corresponding labels for the pull requests were missing in the GitHub repository. I had to create these manually so that the release pull requests were labeled correctly. Could this also be a current bug?

Thanks a lot!
