### ISSUE TITLE
Pull request links in changelog use "issue" instead of "pull" in the URLs

### ISSUE THREAD

**Issue by WillGibson** [googleapis/release-please-action#1079]
If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: Python, though I'm not sure that has any bearing.
  - OS: Ubuntu 24.04.1
  - Language runtime version: 3.12.4, though I'm not sure that has any bearing.
  - Package version: 16.12.0

#### Steps to reproduce

Use release please-action with the following configuration...

```yaml
# .github/workflows/create-release.yml
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-config.json
          manifest-file: release-manifest.json
```

```json
# release-config.json
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "packages": {
    ".": {
        "release-type": "python",
        "include-v-in-tag": false,
        "draft": false,
        "pull-request-header": ":robot: Next release",
        "pull-request-footer": " "
    }
  }
}
```

CHANGELOG.md includes links like this...

```
[#764](https://github.com/uktrade/platform-tools/issues/764)
```

...when we would expect...

```
[#764](https://github.com/uktrade/platform-tools/pull/764)
```
