### ISSUE TITLE
PR branch no longer deleted after merge and squash

### ISSUE THREAD

**Issue by Norbz** [googleapis/release-please-action#1100]
I used to have the PR branched automatically deleted when accepting the merge (using merge and squash), but it seems to no longer to be the case. While it's not a big deal, it was nice to have it done automatically

#### Environment details

  - Programming language: NodeJS
  - OS: MacOS
  - Language runtime version: Node V20
  - Package version: release-please-action@latest

Release-please.yml
```
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: main
```

release-please-config.json
```
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "packages": {
    ".": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "node",
      "changelog-sections": [
        { "type": "feat", "section": "🚀 New Features", "hidden": false },
        { "type": "feature", "section": "🚀 New Features", "hidden": false },
        { "type": "enhance", "section": "💅 Enhancements", "hidden": false },
        { "type": "fix", "section": "🔥 Bug Fixes", "hidden": false },
        { "type": "perf", "section": "🏃 Performance Improvements", "hidden": false },
        { "type": "docs", "section": "📚 Documentation", "hidden": false },
        { "type": "style", "section": "🎨 Polish", "hidden": false },
        { "type": "chore", "section": "⚙️ Chores", "hidden": false },
        { "type": "refactor", "section": "⌨️ Code Refactoring", "hidden": false },
        { "type": "ci", "section": "📦 CI Improvements", "hidden": true },
        { "type": "build", "section": "🛠️ Build System", "hidden": true },
        { "type": "revert", "section": "↩️ Reverts", "hidden": true },
        { "type": "test", "section": "🧪 Automated Testing", "hidden": true }
      ]
    }
  }
}
```

#### Steps to reproduce

  1. Add some commits to the main branch
  2. Release Please makes a PR
  3. Merge and squash the PR
  4. Branch is not deleted after the automatic comment made by release-please

![Image](https://github.com/user-attachments/assets/186aa0f8-bcaa-4cc7-a89c-49ea5dd235c0)

Thanks!
