### ISSUE TITLE
Missing versioning and prerelease action inputs

### ISSUE THREAD

**Issue by b0lle** [googleapis/release-please-action#1101]
I try to use release-please to create prerelease versions like v1.0.0-beta.1 und then make a stable version from it (v1.0.0). For this I need a way to manipulate either the ["prerelease" property](https://github.com/googleapis/release-please/blob/422df5a6a9d44a52c6c682563d1795b8fd246215/docs/manifest-releaser.md?plain=1#L200) or the ["versioning" property](https://github.com/googleapis/release-please/blob/422df5a6a9d44a52c6c682563d1795b8fd246215/schemas/config.json#L27) of release-please.

Is there any reason why those (and some other configuration properties, which are present in release-please) are not configurable through this action?

**Comment by chgl** [comment]
While a separate pre-release config is one way, being able to set the `prerelease` and `prerelease-type` settings as workflow parameters would be incredibly useful to do releases from different branches corresponding to different pre-releases. I.e. what semantic-release allows as well. For example, a workflow could look like this:

```yaml
name: "Release Please"

on:
  push:
    branches:
      - main
      - beta
      - rc

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # everything but main is a pre-release
          prerelease: ${{ github.ref_name != 'refs/heads/main' }}
          # the type is the same as the name of the branch (beta, rc)
          prerelease-type: ${{ github.ref_name }}
```

Although I am admittedly not 100% sure this works, especially when it comes to promoting releases between branches.
