### ISSUE TITLE
Hooks for running commands after files update

### ISSUE THREAD

**Issue by S1M0N38** [googleapis/release-please-action#1102]
### Context

I have a Python project using Astral's `uv` for dependency management. When release-please creates a new version, I need to update `uv.lock` to match.

Currently, this happens in a separate commit after release:

```yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Release tag

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: python

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
          ref: main

      - name: Install uv
        if: ${{ steps.release.outputs.release_created }}
        uses: astral-sh/setup-uv@v5

      - name: Configure Git
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update lock file
        if: ${{ steps.release.outputs.release_created }}
        run: uv lock

      - name: Commit and push updated lock file
        if: ${{ steps.release.outputs.release_created }}
        run: |
          if [[ -n $(git status --porcelain uv.lock) ]]; then
            git add uv.lock
            git commit -m "chore(deps): update uv.lock for version ${{ steps.release.outputs.version }}"
            git push
          else
            echo "No changes to uv.lock"
          fi
```

### Why updating after tag is problematic

Updating the lock file after the release tag creates several issues:

1. The tagged release doesn't match the actual dependencies needed for the version
2. Anyone checking out the tag will get an incorrect/outdated `uv.lock` file
3. Build reproducibility is compromised as the lock file isn't synchronized with the code version
4. The separate commit creates a state in the repository that wasn't properly tested before release

### Question

Does release-please have any hooks or mechanisms to run commands (like `uv lock`) during PR creation, allowing generated files to be included in the release PR itself rather than added after the tag?

### Environment
- Python project using astral.sh uv
- Using release-please-action@v4 with release-type: python

**Comment by S1M0N38** [comment]
I don't think that with this approach you can run custom comands like `uv lock`.

**Comment by JonasCir** [comment]
Correct, you cannot. But your lock file will be up-to-date in the release, so there is no need to run `uv lock` in the first place.

**Comment by mischavandenburg** [comment]
Thank you @JonasCir this worked perfectly!

**Comment by ferrarimarco** [comment]
There's currently no support for this at the moment, and it's likely out of scope for release-please.

As a workaround, either you can:

- Prepare your release assets (eg: running `uv lock`) in a dedicated commit before merging the release-please PR
- Prepare your release assets in a dedicated commit after merging the release-please PR and overwrite the Git tag, because Git tags are not immutable (and also one the reasons behind the recommendation to pinning dependencies by commit hash instead of version tags)

**Comment by Julusian** [comment]
I am hitting a similar issue using a yarn4 monorepo.

I need to update the `0.2.2` values in this block:
```
"@my-pkg/core@npm:0.2.2, @my-pkg/core@workspace:packages/core":
  version: 0.0.0-use.local
  resolution: "@my-pkg/core@workspace:packages/core"
  dependencies:
    tslib: "npm:^2.8.1"
  languageName: unknown
  linkType: soft

"@my-pkg/node@workspace:packages/node":
  version: 0.0.0-use.local
  resolution: "@my-pkg/node@workspace:packages/node"
  dependencies:
    "@my-pkg/core": "npm:0.2.2"
    tslib: "npm:^2.8.1"
  languageName: unknown
  linkType: soft
```
Maybe this is possible with the extra-files options (I havent tried), but it will be horrible to write and maintain.
Additionally, updating even just the package.json files is very verbose, having to update the dependencies one at a time. 

All of this makes it a __very__ brittle setup that will need tweaks each time a package reference within the monorepo is added. 

If I could instead run `yarn workspaces foreach --all version 0.2.3` or `yarn version 0.2.3` (depending on how things are setup), then yarn will handle all of this for me.

----

I have a workaround, which is to check the output of the action to see when it creates/updates a pr, and push a second commit to that branch of my custom syncing logic.
This is a suboptimal solution, as it is a wordier github actions workflow, and will waste ci minutes due to it being 2 pushes, but is better than nothing.


```

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config.json

      - name: PR info
        if: steps.rp.outputs.prs_created == 'true'
        run: |
          echo "prs_created=${{ steps.rp.outputs.prs_created }}"
          echo "pr_number=${{ fromJSON(steps.rp.outputs.pr).number }}"
          echo "pr_branch=${{ fromJSON(steps.rp.outputs.pr).headBranchName }}"

      - name: Checkout PR branch
        if: steps.rp.outputs.prs_created == 'true' && steps.rp.outputs.pr != ''
        uses: actions/checkout@v5
        with:
          ref: ${{ fromJSON(steps.rp.outputs.pr).headBranchName }}
          persist-credentials: true
          fetch-depth: 0

      - name: Sync version changes
        if: steps.rp.outputs.prs_created == 'true'
        run: |
          corepack enable
          yarn install

          # Update versions
          NEW_VERSION=$(node -p "require('./package.json').version")
          yarn workspaces foreach --all version $NEW_VERSION

      - name: Auto-commit & push
        if: steps.rp.outputs.prs_created == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(release): sync versions'
          file_pattern: yarn.lock packages/*/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
