### ISSUE TITLE
Fails to create label when action runs

### ISSUE THREAD

**Issue by ralphsmith80** [googleapis/release-please-action#1105]
#### Environment details

  - Programming language: JavaScript
  - OS: Windows
  - Language runtime version: Node
  - Package version: v4

#### Steps to reproduce

  1. Create a free Organization GitHub account
  2. Create a repository
  3. create a `release-please.yml` with the documented contents for GitHub Actions, but use the special `secrets.GITHUB_TOKEN` token. 

```
on:
  push:
    branches:
      - main

permissions:
  issues: write # This is important for label creation
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
```
  4. Run the action 

**Expected Behavior:**
1. the action runs successfully

**Actual Behavior:**
1. The action fails trying to create a label
```
Error: release-please failed: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
```
2. The PR is opened successfully still [example](https://github.com/QuantAlchemy/quant-companion/pull/3)

My understanding is that the `pull-requests: write` config option should allow for this permission. Is it trying to assign an existing label or actually create a new one?
