### ISSUE TITLE
Self triggering Release-Please Action

### ISSUE THREAD

**Issue by AlpineWeezl** [googleapis/release-please-action#1107]
Hi there

I create a Spring boot (Maven) and try to use Release-Please with the default settings.
The `Squash and Merge` of the first PR seems to work fine until I `Squash and Merge` the automatically created PR. Then it seems that Release-Please triggers itself and then throws errors.
Further attempts end similarly.

I have two questions for this:
1. What I'm doing wrong in the workflow?
2. Can it be repaired?

Thanks four your help!

```yml
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RP_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: java
```

```
❯ found 2 possible releases. [
  Version {
    major: 1,
    minor: 0,
    patch: 0,
    preRelease: undefined,
    build: undefined
  },
  Version {
    major: 1,
    minor: 0,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building pull requests
✔ Building strategies by path
❯ .: java
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v1.0.0
❯ release for path: ., version: 1.0.0, sha: 10c6d9c3565ee6a6d510f30fe7ce01ffcbcc4c23
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { '10c6d9c3565ee6a6d510f30fe7ce01ffcbcc4c23' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 155d5d9f46ec7c021154d05934c39a6aa519f864
❯ Found 4 files
❯ Backfilling file list for commit: 25bcae3c348bd2f110e8700071880cfa26b97905
❯ Found 1 files
❯ Backfilling file list for commit: be563f8883a816ed8959d98e9b767837043264c0
❯ Found 2 files
❯ Backfilling file list for commit: 305d74f634a720665b797d0bd1bd11327df50764
❯ Found 1 files
❯ Backfilling file list for commit: 55767fd54976ed23eee16fbc1da6d2b7eb766423
❯ Found 9 files
✔ Splitting 0 commits by path
✔ Building candidate release pull request for path: .
❯ type: java
❯ targetBranch: main
❯ commits: 0
❯ component: 
✔ Repository needs a snapshot bump.
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
✔ Empty change set provided. No changes need to be made. Cancelling workflow.
Error: release-please failed: Not Found
```
