### ISSUE TITLE
Must specify `include-component-in-tag` in both GH action parameters *and* manifest config

### ISSUE THREAD

**Issue by TylerGillson** [googleapis/release-please-action#1112]
#### Steps to reproduce

  1. Specify `include-component-in-tag: true` in your manifest config (e.g., `release-please-config.json`)
  2. Omit the same from your Github action step's input parameters, e.g.:
      ```yaml
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release
        with:
          token: ${{ steps.import-secrets.outputs.VAULT_GITHUB_TOKEN }}
      ```
  3. Trigger the Github action and inspect the runtime parameters

Note that `include-component-in-tag: false` is overridden by omission:

<img width="644" alt="Image" src="https://github.com/user-attachments/assets/f1d2c598-31e3-4dd3-a786-fa613a6358e3" />
