### ISSUE TITLE
get back changelog-sections 🙏

### ISSUE THREAD

**Issue by tanguyantoine** [googleapis/release-please-action#1114]
**Is your feature request related to a problem? Please describe.**
I'm using release-please within an organization context. it is very powerful and it is a must-have when comes time to deploy applications.
The objective would be to roll out this action wrapped within a reusable github workflow so that it comes with a pre-existing set of configuration.
ex
```yaml
name: 'release-please'
on:
  workflow_call:
  # eventually add debug input
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: debug
        run: |
          echo "Release PR: ${{ steps.release.outputs.releases_created }}"
```

**Describe the solution you'd like**
I wish I could specify the `changelog-sections` from this workflow so that I don't need to repeat it in every repository that use it the repo above
```yaml
name: 'release-please'
on:
  workflow_call:
  # eventually add debug input
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ARGOCD_AUTO_DEPLOY_GH_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          changelog-sections: |
            [
              {"type":"feat","section":"🚀 Features","hidden":false},
              {"type":"change","section":"🚀 Features","hidden":false},
              {"type":"deprecate","section":"⚠️ Changes","hidden":false},
              {"type":"remove","section":"⚠️ Changes","hidden":false},
              {"type":"fix","section":"🐞 Bug Fixes","hidden":false},
              {"type":"revert","section":"🐞 Bug Fixes","hidden":false},
              {"type":"security","section":"🐞 Bug Fixes","hidden":false},
              {"type":"perf","section":"✨ Polish","hidden":false},
              {"type":"refactor","section":"✨ Polish","hidden":false},
              {"type":"style","section":"✨ Polish","hidden":false},
              {"type":"build","section":"🧰 Other","hidden":false},
              {"type":"chore","section":"🧰 Other","hidden":false},
              {"type":"deps","section":"🧰 Other","hidden":true},
              {"type":"ci","section":"🧰 Other","hidden":true},
              {"type":"test","section":"🧪 Tests","hidden":false},
              {"type":"docs","section":"📚 Documentation","hidden":false}
            ]

```

**Describe alternatives you've considered**
replicate within each repo but this is not convenient
