### ISSUE TITLE
Two pull requests. After merging the first one,  merging the second one won't create release pull request

### ISSUE THREAD

**Issue by hongmingavaya** [googleapis/release-please-action#902]
### TL;DR

There are two pull requests pending for approval.  Each of them has conventional commit messages (fix:xxx).  Merging of second one won't create a release pull request after the first one has been merged.

### Expected behavior

1. Create a branch A based on latest main branch, make some changes with commit comment “fix:A”, then create a pull request A to merge the changes in branch A into main branch.

2. Create a branch B based on latest main branch, make some changes with commit comment to “fix:B”, then create a pull request B to merge the changes in branch B into main branch.

3. Merge pull request A into main branch,  the changes in pull request A is successfully merged into main branch and a new release A is cut.
  
4. Merge pull request B into main branch,  the changes in pull request B is successfully merged into main branch and a new release pull request is created.

### Observed behavior

4. Merge pull request B into main branch,  the changes in pull request B is successfully merged into main branch and no new release pull request is created and following log is displayed:

❯ targetBranch: main
❯ commit could not be parsed: 9f7c798637181f4ea10624b1f9ef8ae57028e236 Merge pull request #159 from 
customer/testbranch
❯ **commits: 0**
✔ Considering: 0 commits
✔ No commits for path: ., skipping

### Action YAML

```yaml
- name: Create pull request
        id: create_pr
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: main
          monorepo-tags: true
          component: main
          labels: |
            autorelease: pending
            automerge

      - name: Approve pull request 1
        id: approve_pr_1
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: token1
          pull-request-number: ${{ fromJson(steps.create_pr.outputs.pr).number }}

      - name: Merge pull Request
        id: merge_pr
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ steps.create_pr.outputs.pr && fromJson(steps.create_pr.outputs.pr).number }}
          UPDATE_METHOD: merge

      - name: Release Version
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: main
          monorepo-tags: true
          component: main
          token: token1
```
